MODEL:
  VID:
    ENABLE: True
    METHOD: "JF_cvc_mega"
    ROI_BOX_HEAD:
      REDUCE_CHANNEL: True
      ATTENTION:
        ENABLE: True
        STAGE: 3
    MEGA:
      GLOBAL:
        RES_STAGE: 0
  META_ARCHITECTURE: "GeneralizedRCNNMEGA"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-C4"
  ROI_BOX_HEAD:
    NUM_CLASSES: 3
    POOLER_RESOLUTION: 7
    FEATURE_EXTRACTOR: "MEGAFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("JF_KUMC",)
  TEST: ("JF_KUMC_VAL",) #2484 frames, subdir in ['2','5','10','18']
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 1
  WARMUP_METHOD: "linear"
  WARMUP_ITERS: 2000
  CHECKPOINT_PERIOD: 500
  TEST_PERIOD: 500
  MAX_ITER: 60000
  LR_TYPE: "step"
  GAMMA: 0.5
  STEPS: (0, 30000, 40000)
TEST:
  IMS_PER_BATCH: 1
DATALOADER:
  NUM_WORKERS: 4