MODEL:
  VID:
    ENABLE: False
    METHOD: "JF_cvc_image"
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  RETINANET_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STAGE_WITH_DCN: (False, True, True, True)
    WITH_MODULATED_DCN: False
    DEFORMABLE_GROUPS: 1
    STAGE_WITH_GCB: (False, True, True, True)
  RETINANET:
    NUM_CLASSES: 3
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ASPECT_RATIOS: (0.5, 1.0, 2.0)
    ANCHOR_STRIDES: (8, 16, 32, 64, 128)
    SCALES_PER_OCTAVE: 3
    STRADDLE_THRESH: -1
    FG_IOU_THRESHOLD: 0.5
    BG_IOU_THRESHOLD: 0.4
DATASETS:
  TRAIN: ("JF_KUMC",)
  TEST: ("JF_KUMC_VAL",)
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 1
  WARMUP_METHOD: "linear"
  WARMUP_ITERS: 2000
  CHECKPOINT_PERIOD: 500
  TEST_PERIOD: 500
  MAX_ITER: 24000
  LR_TYPE: "step"
  GAMMA: 0.5
  STEPS: (0, 30000, 40000)
TEST:
  IMS_PER_BATCH: 1
  DETECTIONS_PER_IMG: 300
DATALOADER:
  NUM_WORKERS: 4
