MODEL:
  VID:
    ENABLE: True
    METHOD: "cvc_stft"
    STFT:
      MIN_OFFSET: -9
      MAX_OFFSET: 9
      TRAIN_REF_NUM: 2
      TEST_REF_NUM: 10
  META_ARCHITECTURE: "GeneralizedRCNNSTFT"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  FCOS_ON: True
  STFT_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STAGE_WITH_DCN: (False, True, True, True)
    WITH_MODULATED_DCN: False
    DEFORMABLE_GROUPS: 1
    STAGE_WITH_GCB: (False, True, True, True)
  RETINANET:
    USE_C5: False
  FCOS:
    NUM_CLASSES: 2
    FPN_STRIDES: [8, 16, 32, 64, 128]
    INFERENCE_TH: 0.05
    NMS_TH: 0.6
    PRE_NMS_TOP_N: 1000
    NORM_REG_TARGETS: True
    CENTERNESS_ON_REG: True
    CENTER_SAMPLING_RADIUS: 1.5
    IOU_LOSS_TYPE: "giou"
  STFT:
    OFFSET_WEIGHT_STD: 0.01
    IOU_THRESH: 0.1
    BBOX_STD: [0.5, 0.5, 0.5, 0.5]
    REG_BETA: 0.11
DATASETS:
  TRAIN: ("sundatabase_stft_train_videos",)
  TEST: ("sundatabase_stft_val_videos",) 
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  # https://github.com/facebookresearch/Detectron/blob/main/configs/getting_started/tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml#L14
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 4
  WARMUP_METHOD: "linear"
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 250
  TEST_PERIOD: 125
  MAX_ITER: 15000
  LR_TYPE: "step"
  GAMMA: 0.5
  STEPS: (0, 7500, 10000)
TEST:
  IMS_PER_BATCH: 4
  DETECTIONS_PER_IMG: 300
DATALOADER:
  NUM_WORKERS: 4
